# Generated by Django 4.2.2 on 2023-06-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Color Shade')),
                ('cat', models.IntegerField(choices=[(1, 'Oil-Based'), (2, 'Water-Based')], verbose_name='Category')),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
